version: "3"
services:
  backend:
    build: ./backend
    environment:
      - DB_HOST=database
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
    ports:
      - "3000:3000"
  database:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    expose:
      - "5432"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
  keycloak:
    build: ./keycloak
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      SYNC_USERS_DB_HOST: database
      SYNC_USERS_DB_NAME: "${DB_NAME}"
      SYNC_USERS_DB_USER: "${DB_USER}"
      SYNC_USERS_DB_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "8080:8080"
    command: ["start-dev"]
