name: CI

on:
  push:
  pull_request:

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: cd camera
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          echo $(pwd)
          pip install -r ./requirements.txt
      - name: Run tests
        run: make test
