name: CI

on:
  push:

jobs:
  pi-auth-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Update apt and install system dependencies
        run: |
          sudo apt-get update && sudo apt-get upgrade
          sudo apt-get install build-essential libcairo2-dev libgirepository1.0-dev libdbus-glib-1-dev
      - name: Install dependencies
        working-directory: ./camera/auth
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Run tests
        working-directory: ./camera/auth
        run: make test
      - name: Run lint
        working-directory: ./camera/auth
        run: make lint

  pi-detector-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        working-directory: ./camera/detector
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Run tests
        working-directory: ./camera/detector
        run: make test

  app-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        working-directory: ./app/human-detector-app
        run: npm ci
      - name: Run tests
        working-directory: ./app/human-detector-app
        run: npm test

  app-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        working-directory: ./app/human-detector-app
        run: npm ci
      - name: Run linter
        working-directory: ./app/human-detector-app
        run: npm run lint
  
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build container dependencies
        working-directory: ./server/
        run: docker compose build keycloak
      - name: Install dependencies
        working-directory: ./server/backend
        run: npm ci
      - name: Run tests
        working-directory: ./server/backend
        run: npm test
